name: Build FFmpeg

on:
  workflow_dispatch:

jobs:
  build-cuda-rocky-docker:
    name: Build in Rocky Linux Docker with CUDA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set FFmpeg Latest Version
        id: ffmpeg_version
        run: |
          echo "FFMPEG_VERSION=$(curl -s https://api.github.com/repos/FFmpeg/FFmpeg/tags | grep 'name' | cut -d '\"' -f 4 | head -n 1)" >> $GITHUB_ENV

      - name: Set NVENC Version
        run: |
          echo "NVENC_VERSION=$(curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/rigaya/NVEnc/releases/latest | rev | cut -d '/' -f 1 | rev)" >> $GITHUB_ENV

      - name: Build FFmpeg
        run: |
          docker build --build-arg FFMPEG_VERSION=${{ env.FFMPEG_VERSION }} \
           --build-arg NVENC_VERSION=${{ env.NVENC_VERSION }} -t \
           ffmpeg:cuda-rocky -f cuda-rocky.dockerfile .

      - name: Copy Build
        run: |
          docker run --rm  -v ${{ github.workspace }}/artifacts:/app/artifacts \
           ffmpeg:cuda-rocky bash copyfiles.sh
          sudo chmod -R 777 ${{ github.workspace }}/artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg
          path: artifacts/*

  publish_release:
    name: Publish Release
    needs: build-cuda-rocky-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg
          path: artifacts

      - name: Set FFmpeg Latest Version
        id: ffmpeg_version
        run: |
          echo "FFMPEG_VERSION=$(curl -s https://api.github.com/repos/FFmpeg/FFmpeg/tags | grep 'name' | cut -d '\"' -f 4 | head -n 1)" >> $GITHUB_ENV

      - name: Set NVENC Version
        run: |
          echo "NVENC_VERSION=$(curl -fsSLI -o /dev/null -w %{url_effective} https://github.com/rigaya/NVEnc/releases/latest | rev | cut -d '/' -f 1 | rev)" >> $GITHUB_ENV

      - name: Delete Release
        run: gh release delete latest --cleanup-tag -y
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      
      - name: Upload Modules to Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.PAT }}
          tag_name: latest
          files: ${{ github.workspace }}/artifacts/**/*
          name: FFmpeg-${{ env.FFMPEG_VERSION }}-Nvencc-${{ env.NVENC_VERSION }}
          draft: false
          prerelease: false
